- name: Enable nginx PPA
  apt_repository: repo=ppa:nginx/stable
  tags: [nginx]

- name: Install nginx
  apt: name=nginx state=present
  tags: [nginx]

- name: Configure Backend App nginx
  template: src=nginx_unicorn.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}
  notify: restart nginx
  tags: [nginx]

- name: Restart nginx
  service: name=nginx state=restarted
  tags: [restart_nginx]

- name: Ditch default nginx site enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: [nginx]
