- name: Install VIM
  apt: name=vim state=present

- name: Install Build-Essential
  apt: name=build-essential state=present

- name: Install GIT
  apt: name=git state=present

- name: Install IM
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev

- name: Install curl
  apt: name=curl state=present

- name: Get current node version
  command: bash -lc "node -v"
  register: node_version
  ignore_errors: yes

- name: Download nodejs source
  command: bash -lc "curl http://nodejs.org/dist/v{{node.version}}/node-v{{node.version}}.tar.gz > node-v{{node.version}}.tar.gz"
  when: node_version.stdout != "v{{node.version}}"

- name: Untar nodejs
  command: bash -lc "tar -zxf node-v{{node.version}}.tar.gz"
  when: node_version.stdout != "v{{node.version}}"

- name: Install Nodejs
  command: chdir="node-v{{node.version}}"
           bash -lc "./configure && make && sudo make install"
  when: node_version.stdout != "v{{node.version}}"

- name: Install npm
  command: bash -lc "curl -L https://npmjs.com/install.sh | sh"

- name: Install coffee-script for smashing-dev-tool
  npm: name=coffee-script global=yes

- name: Install bower for smashing-dev-tool
  npm: name=bower global=yes

- name: Install smashing dev tool
  npm: name=smashing-dev-tool global=yes
