---
- hosts: omnibox
  user: root

  vars_files:
    - "{{tape_dir}}/vars/defaults.yml"
    - tape_vars.yml

  roles:
    - general
    - deployer_user
    - frontend_install_essentials
    - monit_install
    - nginx
    - frontend_deploy
    - monit_activate # Run Last
