- name: Ensure tmp dir present for unicorn pids
  file: state=directory path={{be_app_path}}/tmp/unicorn owner={{ deployer_user.name }}
  tags: [be_deploy]

- name: Restart Unicorn
  command: bash -lc "service unicorn_{{ app_name }} upgrade"
  tags: [unicorn_restart,be_deploy]

- name: Ensure unicorn is running
  service: name=unicorn_{{app_name}} state=started
  tags: [unicorn_restart,be_deploy,unicorn_start]

- name: Ensure unicorn is stopped
  command: bash -lc "pkill -9 -f unicorn"
  when: kill_unicorn
  tags: [unicorn_stop]
