- name: Ensure tmp dir present for unicorn pids
  file: state=directory path={{be_app_path}}/tmp/unicorn owner={{ deployer_user.name }}
  tags: [be_deploy]

- name: Ensure unicorn is running
  command: bash -lc "service unicorn_{{ app_name }} start"
  tags: [be_deploy,unicorn_start]

- name: Restart Unicorn
  command: bash -lc "service unicorn_{{ app_name }} restart"
  tags: [unicorn_restart,be_deploy]

- name: Ensure unicorn is stopped
  command: bash -lc "service unicorn_{{ app_name }} stop"
  when: kill_unicorn
  tags: [unicorn_stop]

- name: Force stop unicorn
  command: bash -lc "service unicorn_{{ app_name }} force-stop"
  when: kill_unicorn
  tags: [unicorn_force_stop]
