- name: Ensure tmp dir present for unicorn pids
  file: state=directory path={{be_app_path}}/tmp/unicorn owner={{ deployer_user.name }}
  tags: [be_deploy]

- name: reload unicorn
  sudo_upstart: name=unicorn_{{app_name}} state=reloaded
  remote_user: "{{ deployer_user.name }}"
  tags: [be_deploy,unicorn_reload]
  when: (app_checkout is defined and app_checkout.changed) or force_unicorn_reload

- name: restart unicorn
  sudo_upstart: name=unicorn_{{app_name}} state=restarted
  tags: [unicorn_restart,be_deploy]
  when: force_unicorn_restart

- name: stop unicorn
  command: bash -lc "pkill -9 -f unicorn"
  when: force_unicorn_stop
  tags: [unicorn_stop]

- name: Ensure unicorn is running
  sudo_upstart: name=unicorn_{{app_name}} state=started
  remote_user: "{{ deployer_user.name }}"
  tags: [unicorn_start,be_deploy]
