---
- hosts: omnibox
  user: root

  vars_files:
    - vars/defaults.yml
    - "{{lookup('env', 'PWD')}}/site_vars.yml"


  roles:
    - general
    - postgres
    - nginx
    - backend_install_essentials
    - frontend_deploy
    - backend_config
    - unicorn_install
    - database_load
    - unicorn_activate
    - delayed_job
