---
- hosts: omnibox
  user: root

  vars_files:
    - vars/defaults.yml
    - "{{lookup('env', 'PWD')}}/site_vars.yml"

  roles:
    - general
    - postgres
    - nginx
    - backend_install_essentials
    - deployer_user
    - backend_checkout
    - unicorn_install
    - backend_config
    - database_load
    - unicorn_activate
    - frontend_deploy
    - delayed_job
    - after_deploy
