---
- hosts: omnibox
  user: root

  vars_files:
    - vars/defaults.yml
    - "{{lookup('env', 'PWD')}}/site_vars.yml"


  roles:
    - apt_update
    - before_database
    - postgres
    - before_general
    - swap_file
    - install_essentials
    - before_web
    - nginx
    - front_end
    - rbenv
    - before_ruby
    - bundle_environment
    - before_app_server
    - unicorn
    - load_database
    - rails_config
    - delayed_job
