---
- hosts: omnibox
  user: root

  vars_files:
    - vars/defaults.yml
    - "{{local_dir}}/site_vars.yml"


  roles:
    - database
    - general
    - web
    - legacy
    - gems
    - app_server
    - delayed_job
