---
- hosts: omnibox
  user: root

  vars_files:
    - vars/defaults.yml
    - "{{local_dir}}/site_vars.yml"


  roles:
    - before_database
    - database
    - before_general
    - general
    - before_web
    - web
    - legacy
    - before_ruby
    - gems
    - before_app_server
    - app_server
    - delayed_job
