---
- src: jnv.unattended-upgrades
  version: v1.0.1

- src: zzet.rbenv
  version: 2.0.0

- src: lxhunter.apt

- src: https://github.com/ANXS/postgresql
  name: ANXS.postgresql

- src: leonelgalan.node
  version: '0.2'

- src: bennojoy.memcached
