- name: Install monit
  apt: name=monit state=present

- name: Register monit config files
  template: src={{ item }}.j2
            dest=/etc/monit/conf.d/{{ item }}
            mode=u=rw,g=r,o=r
  with_items:
   - memcached
   - nginx
   - redis
   - sidekiq
   - unicorn
   - web_interface

- name: Reload monit
  command: bash -lc "monit reload"
