---
- name: Update caches
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Create general configuration file for APT
  template:
    src: apt_10general.j2
    dest: /etc/apt/apt.conf.d/10general
    owner: root
    group: root
    mode: 0644

- name: Install apt packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    [python-apt, unattended-upgrades]

- name: Install packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    apt_install_packages
  when: apt_install_packages is defined

- name: Update parameters
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} \"{{ item.value }}\";"
    insertafter: EOF
  with_items: apt_unattended_upgrades_config
  when: apt_unattended_upgrades_config is defined