- name: Install VIM
  apt: name=vim state=present

- name: Install Build-Essential
  apt: name=build-essential state=present

- name: Install GIT
  apt: name=git state=present

- name: Install IM
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev


- name: Update node.js package
  command: bash -lc "curl -sL https://deb.nodesource.com/setup | sudo bash -"

- name: Install node.js
  apt: name=nodejs state=present
