- name: Install VIM
  apt: name=vim state=present

- name: Install BUILD-ESSENTIAL
  apt: name=build-essential state=present

- name: Install GIT
  apt: name=git state=present

- name: Install CURL
  apt: name=curl state=present

- name: Install NODEJS
  apt: name=nodejs state=present

- name: Install NPM
  command: bash -lc "curl -L https://npmjs.com/install.sh | sh"

- name: Install N
  npm: name=n global=yes

- name: Upgrade NODEJS
  command: bash -lc "n stable"
