- stat: path="{{ be_app_path }}/tmp/sidekiq.pid"
  register: sidekiq_pid
  tags: [be_deploy, unicorn_stop, unicorn_start]

- name: Stop sidekiq
  remote_user: "{{deployer_user.name}}"
  command:
    chdir={{be_app_path}}
    bash -lc "bundle exec sidekiqctl shutdown {{ sidekiq_pid }}"
  tags: [unicorn_stop]
  when: sidekiq_pid.stat.exists

- name: Start sidekiq
  remote_user: "{{deployer_user.name}}"
  command:
    chdir={{be_app_path}}
    bash -lc "bundle exec sidekiq -d -L log/sidekiq.log -e {{be_app_env}} -P {{ sidekiq_pid }}"
  tags: [be_deploy, unicorn_start]
