- name: Ensure deployer user is present
  user: name=deployer state=present append=yes shell=/bin/bash

# It's possible for the deployer's homedir to get created on accident by
# a deploy script or something getting run before this.  This just ensures
# the env is sane moving forward
- name: Ensure deployer user owns his own homedir
  file: path=/home/deployer state=directory owner=deployer

- include: keys.yml
