- name: rsync the FE app
  remote_user: "{{ deployer_user.name }}"
  synchronize:
    src={{ fe_app_local_path }}
    dest={{ fe_app_path }}
  tags: [fe_deploy]
  register: fe_app_checkout
  when: fe_app_path is defined
