- name: Install DJ monit bin command
  template: src=dj_monit_runner.j2
            dest=/usr/bin/dj_monit_runner
            mode=u=rwx,g=rwx,o=r

- name: Install DJ monit config
  template: src=dj_monit_config.j2
            dest=/etc/monit/conf.d/delayed_jobs
            mode=u=rw,g=r,o=r
  register: dj_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: dj_monit_config.changed

- name: Restart Delayed Job
  remote_user: "{{ deployer_user.name }}"
  command: bash -lc "sudo monit stop delayed_job"
  tags: [be_deploy]

- name: Restart Delayed Job
  remote_user: "{{ deployer_user.name }}"
  command: bash -lc "sudo monit start delayed_job"
  tags: [be_deploy]
