- name: Enable nginx PPA
  apt_repository: repo=ppa:nginx/stable
  tags: [nginx]

- name: Install nginx
  apt: name=nginx state=present
  tags: [nginx]

- name: Configure nginx
  template: src=nginx_unicorn.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}
  notify: restart nginx
  tags: [nginx]

- name: Restart nginx
  service: name=nginx state=restarted
  tags: [restart_nginx]

- name: Ditch default nginx site enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: [nginx]

- name: Install coffeescript
  npm: name=coffee-script global=yes

- name: Install bower
  npm: name=bower global=yes

- name: Install smashing-dev-tool
  remote_user: deployer
  git:  dest="/home/{{ deployer_user.name }}/smashing-dev-tool"
        repo=git@github.com:smashingboxes/smashing-dev-tool.git
        accept_hostkey=true
  when: fe_app
  tags: [fe]

- name: Link smashing-dev-tool
  remote_user: deployer
  command:  chdir="/home/{{ deployer_user.name }}/smashing-dev-tool"
            bash -lc "npm link"

- name: Check out FE application
  remote_user: deployer
  git: dest={{ fe_app_path }}
       repo={{ fe_app_repo }}
       version={{ fe_app_branch }}
       accept_hostkey=true
  when: fe_app
  tags: [deploy, fe]
  register: fe_app_checkout
  
- name: Install node packages for web FE
  remote_user: deployer
  command: chdir={{fe_app_path}}
           bash -lc "bower install"
  tags: [deploy, fe]
  when: (fe_app_checkout is defined and fe_app_checkout.changed) or
        force_fe_build|default(false)

- name: Build FE app
  remote_user: deployer
  command: chdir={{fe_app_path}}
           bash -lc "grunt build"
  tags: [deploy, fe]
  when: (fe_app_checkout is defined and fe_app_checkout.changed) or
        force_fe_build|default(false)

- name: Ensure nginx running
  remote_user: deployer
  service: name=nginx state=running
  tags: [deploy, fe]
