- name: Install IM
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev

- name: Install bundler
  gem: executable=/usr/local/rbenv/shims/gem name=bundler user_install=no
  notify: rbenv rehash
