- name: Migrate DB
  remote_user: deployer
  command: chdir={{ app_path }}
           bash -lc "bundle exec rake db:migrate RAILS_ENV={{app_env}}"
  run_once: true
  when: migrate is defined and migrate

- name: Seed DB
  remote_user: deployer
  command: chdir={{ app_path }}
           bash -lc "bundle exec rake db:seed RAILS_ENV={{app_env}}"
  run_once: true
  when: seed is defined and seed
